/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/actuator/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Actuator web endpoint 'health' */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search names and faces within a jointly eligible printing pool */
        get: operations["searchCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{oracle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a card with every canonical face */
        get: operations["getCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{oracle_id}/printings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jointly eligible printings for a card */
        get: operations["listPrintings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get application version and available capabilities */
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published catalogs, active first */
        get: operations["listSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{catalog_snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect catalog provenance and available sets */
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Attribution: {
            label: string;
            url: string;
        };
        CardDetail: {
            catalog_snapshot_id: string;
            color_identity: string[] | null;
            colors: string[] | null;
            faces: components["schemas"]["Face"][];
            layout: string;
            mana_cost: string | null;
            /** Format: double */
            mana_value: number | null;
            name: string;
            /** Format: uuid */
            oracle_id: string;
            oracle_text: string | null;
            type_line: string | null;
        };
        CardPage: {
            catalog_snapshot_id: string;
            items: components["schemas"]["CardSummary"][];
            next_cursor: string | null;
        };
        CardSummary: {
            color_identity: string[] | null;
            /** Format: int64 */
            eligible_printing_count: number;
            layout: string;
            name: string;
            /** Format: uuid */
            oracle_id: string;
            preview_printing: components["schemas"]["Printing"];
        };
        CatalogError: {
            /** @enum {string} */
            code: "invalid_query" | "invalid_cursor" | "snapshot_not_found" | "card_not_found" | "catalog_unavailable" | "internal_error";
            detail: string;
            instance: string;
            request_id: string;
            /** Format: int32 */
            status: number;
            title: string;
            type: string;
        };
        Face: {
            colors: string[] | null;
            /** Format: int32 */
            face_index: number;
            mana_cost: string | null;
            name: string;
            oracle_text: string | null;
            type_line: string | null;
        };
        /** @description Application identity and capabilities implemented by this API build. */
        InfoResponse: {
            /** @description Available capabilities; does not advertise planned functionality. */
            capabilities: string[];
            /** @example mtg-scorer-api */
            name: string;
            /**
             * @description API artifact version from the Maven build.
             * @example 0.1.0-SNAPSHOT
             */
            version: string;
        };
        Printing: {
            collector_number: string;
            games: string[];
            images: components["schemas"]["PrintingImage"][];
            language: string;
            rarity: string;
            /** Format: date */
            released_on: string | null;
            /** Format: uuid */
            scryfall_id: string;
            set_code: string;
            set_name: string;
            source_uri: string;
        };
        PrintingImage: {
            artist: string | null;
            /** Format: int32 */
            face_index: number | null;
            source_uri: string;
        };
        PrintingPage: {
            catalog_snapshot_id: string;
            items: components["schemas"]["Printing"][];
            next_cursor: string | null;
            /** Format: uuid */
            oracle_id: string;
        };
        Selection: {
            description: string;
            kind: string;
        };
        SetInfo: {
            set_code: string;
            set_name: string;
        };
        Snapshot: {
            attribution: components["schemas"]["Attribution"][];
            /** Format: int64 */
            card_count: number;
            catalog_snapshot_id: string;
            /** Format: date-time */
            created_at: string;
            excluded_record_counts: {
                [key: string]: number;
            };
            parser_version: string;
            /** Format: int64 */
            printing_count: number;
            /** Format: date-time */
            published_at: string;
            /** Format: date-time */
            retrieved_from: string;
            /** Format: date-time */
            retrieved_to: string;
            schema_version: string;
            selection: components["schemas"]["Selection"];
            sets: components["schemas"]["SetInfo"][];
            source: string;
            tournament_evidence: components["schemas"]["TournamentEvidence"];
        };
        SnapshotList: {
            active_catalog_snapshot_id: string;
            items: components["schemas"]["Snapshot"][];
        };
        TournamentEvidence: {
            reason_codes: string[];
            state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "application/vnd.spring-boot.actuator.v2+json": Record<string, never>;
                    "application/vnd.spring-boot.actuator.v3+json": Record<string, never>;
                };
            };
        };
    };
    searchCards: {
        parameters: {
            query?: {
                catalog_snapshot_id?: string;
                color_identity?: string;
                cursor?: string;
                game?: "arena" | "mtgo" | "paper";
                limit?: number;
                q?: string;
                rarity?: ("bonus" | "common" | "mythic" | "rare" | "special" | "uncommon")[];
                set?: string[];
                sort?: "name_asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardPage"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
        };
    };
    getCard: {
        parameters: {
            query?: {
                catalog_snapshot_id?: string;
            };
            header?: never;
            path: {
                oracle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
        };
    };
    listPrintings: {
        parameters: {
            query?: {
                catalog_snapshot_id?: string;
                cursor?: string;
                game?: "arena" | "mtgo" | "paper";
                limit?: number;
                rarity?: ("bonus" | "common" | "mythic" | "rare" | "special" | "uncommon")[];
                set?: string[];
            };
            header?: never;
            path: {
                oracle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrintingPage"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    listSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotList"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalog_snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
            /** @description Sanitized Problem Details with a stable code */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CatalogError"];
                };
            };
        };
    };
}
